# Generated by Django 4.0.3 on 2022-04-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRestaurante', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='nombre',
        ),
        migrations.AddField(
            model_name='contacto',
            name='nombre_completo',
            field=models.CharField(default='Juan Pérez', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='nombre_completo',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='dia',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='horario',
            field=models.CharField(max_length=5),
        ),
    ]
