# Generated by Django 4.0.3 on 2022-04-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRestaurante', '0003_alter_contacto_local_alter_local_capacidad_exterior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
