# Generated by Django 4.0.3 on 2022-04-07 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppRestaurante', '0005_alter_contacto_local_alter_local_capacidad_exterior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppRestaurante.local'),
        ),
        migrations.AlterField(
            model_name='local',
            name='capacidad_exterior',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
