# Generated by Django 4.0.4 on 2022-05-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRestaurante', '0006_alter_contacto_mensaje_alter_post_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='no_leido',
            field=models.BooleanField(default=True),
        ),
    ]
