# Generated by Django 4.0.4 on 2022-04-25 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRestaurante', '0006_alter_contacto_local_alter_local_capacidad_exterior'),
    ]

    operations = [
        migrations.RenameField(
            model_name='local',
            old_name='capacidad_interior',
            new_name='capacidad',
        ),
        migrations.RemoveField(
            model_name='local',
            name='capacidad_exterior',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='lugar',
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='local',
            name='localidad',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='local',
            name='provincia',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='local',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='menu',
            name='descripcion',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='menu',
            name='tipo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='dia',
            field=models.DateField(),
        ),
    ]
