# Generated by Django 4.0.4 on 2022-04-25 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppRestaurante', '0007_rename_capacidad_interior_local_capacidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='exterior',
        ),
    ]
