# Generated by Django 4.0.4 on 2022-05-05 21:42

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppRestaurante', '0008_alter_mensaje_destinatario_alter_mensaje_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='mensaje',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='contenido',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
