# Generated by Django 4.0.4 on 2022-04-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRestaurante', '0008_remove_local_exterior'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='imagen',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cantidad_personas',
            field=models.PositiveIntegerField(),
        ),
    ]
